name: diff-image-enhancement
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit
  - numpy
  - python=3.10
  - python_abi
  - pytorch
  - matplotlib
  - scipy
  - torchaudio
  - torchvision
  - tqdm=4.64.1
  - pip=22.3.1
  - blobfile
  - pip:
      - tensorboard==2.12.0
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1

